import 'package:flutter/foundation.dart';
import 'package:prostuti/core/utils/json.dart';

/// A follow-up question generated by the `onboarding-interview` function.
@immutable
class AiFollowup {
  const AiFollowup({required this.id, required this.question});

  final String id;
  final String question;

  /// Accepts `[{id, q}]` (also `question`/`text`), skipping blanks.
  static List<AiFollowup> listFrom(Object? raw, {int max = 2}) {
    if (raw is! List) return const [];
    final out = <AiFollowup>[];
    for (final (i, e) in raw.indexed) {
      if (e is Map) {
        final m = Map<String, dynamic>.from(e);
        final q = (m.strOrNull('q') ?? m.strOrNull('question') ?? m.strOrNull('text') ?? '').trim();
        if (q.isEmpty) continue;
        out.add(AiFollowup(id: m.str('id', 'f${i + 1}'), question: q));
      } else if (e is String && e.trim().isNotEmpty) {
        out.add(AiFollowup(id: 'f${i + 1}', question: e.trim()));
      }
      if (out.length >= max) break;
    }
    return out;
  }
}

@immutable
class FollowupAnswer {
  const FollowupAnswer({required this.id, required this.question, required this.answer});

  final String id;
  final String question;

  /// Empty when skipped.
  final String answer;

  Map<String, dynamic> toJson() => {'id': id, 'q': question, 'a': answer};
}

/// The AI's short read of the candidate after the interview.
@immutable
class AiProfile {
  const AiProfile({
    required this.summary,
    this.strengths = const [],
    this.focusAreas = const [],
    this.recommendedDailyMinutes,
    this.raw = const {},
  });

  /// Tolerates `{profile: {...}}` or the bare object; null when unusable.
  static AiProfile? parse(Object? data) {
    if (data is! Map) return null;
    final root = Map<String, dynamic>.from(data);
    final j = root.objOrNull('profile') ?? root;
    final summary = (j.strOrNull('summary_bn') ?? j.strOrNull('summary') ?? j.strOrNull('summary_en') ?? '').trim();
    if (summary.isEmpty) return null;
    final minutes = j.intOrNull('recommended_daily_minutes');
    return AiProfile(
      summary: summary,
      strengths: j.strings('strengths').where((s) => s.trim().isNotEmpty).toList(),
      focusAreas: j.strings('focus_areas').where((s) => s.trim().isNotEmpty).toList(),
      recommendedDailyMinutes: minutes != null && minutes >= 15 && minutes <= 960 ? minutes : null,
      raw: j,
    );
  }

  final String summary;
  final List<String> strengths;
  final List<String> focusAreas;
  final int? recommendedDailyMinutes;
  final Map<String, dynamic> raw;

  Map<String, dynamic> toJson() => raw.isNotEmpty
      ? raw
      : {
          'summary': summary,
          'strengths': strengths,
          'focus_areas': focusAreas,
          'recommended_daily_minutes': recommendedDailyMinutes,
        };
}
