import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:prostuti/core/cache/cached_fetcher.dart';
import 'package:prostuti/core/errors/failure.dart';
import 'package:prostuti/core/network/rpc.dart';
import 'package:prostuti/core/network/supabase_providers.dart';
import 'package:prostuti/core/utils/bd_time.dart';
import 'package:prostuti/features/study_plan/data/daily_advice_models.dart';
import 'package:prostuti/features/study_plan/data/study_plan_repository.dart' show Peeked;
import 'package:supabase_flutter/supabase_flutter.dart';

/// The two backend calls behind the advice (separate so the caching logic
/// can be tested without a network).
abstract interface class DailyAdviceApi {
  String get userId;

  /// Today's stored advice (`get_daily_advice` RPC), or null.
  Future<Map<String, dynamic>?> stored(String locale);

  /// The `daily-advice` Edge Function. Throws an [AppFailure].
  Future<Map<String, dynamic>> generate(String locale, {required bool refresh});
}

class SupabaseDailyAdviceApi implements DailyAdviceApi {
  SupabaseDailyAdviceApi(this._client);

  final SupabaseClient _client;

  static const functionName = 'daily-advice';

  /// The function may call an LLM; give it time before treating it as failed.
  static const timeout = Duration(seconds: 60);

  @override
  String get userId => _client.auth.currentUser?.id ?? 'anon';

  @override
  Future<Map<String, dynamic>?> stored(String locale) async {
    final row = await _client.rpcCall<dynamic>('get_daily_advice', params: {'p_locale': locale});
    return row is Map ? Map<String, dynamic>.from(row) : null;
  }

  @override
  Future<Map<String, dynamic>> generate(String locale, {required bool refresh}) async {
    try {
      final res = await _client.functions
          .invoke(functionName, body: {'locale': locale, 'refresh': refresh})
          .timeout(timeout);
      final data = res.data;
      if (data is! Map) throw const ServerFailure('server_error');
      final map = Map<String, dynamic>.from(data);
      final error = map['error'];
      if (error != null) throw ServerFailure(error.toString());
      return map;
    } on Object catch (e) {
      throw AppFailure.from(e);
    }
  }
}

/// Daily AI advice: today's row through the `get_daily_advice` RPC (one
/// indexed read), generated by the `daily-advice` Edge Function only when
/// there is none yet — normally once per learner per Bangladesh day.
///
/// Cached until Bangladesh midnight; the key is per user + language (not per
/// day), so offline the last copy is still shown, labelled with its date.
class DailyAdviceRepository {
  DailyAdviceRepository(SupabaseClient client, CachedFetcher cache)
    : this.withApi(SupabaseDailyAdviceApi(client), cache);

  @visibleForTesting
  DailyAdviceRepository.withApi(this._api, this._cache);

  final DailyAdviceApi _api;
  final CachedFetcher _cache;

  /// "No advice" (no data yet / allowance used) is re-checked after this.
  static const emptyTtl = Duration(hours: 1);

  String _key(String locale) => 'advice:${_api.userId}:$locale';

  CachePolicy get _policy => CachePolicy(ttl: BdTime.untilEndOfToday(), negativeTtl: emptyTtl);

  /// Cached advice for instant first paint. A copy from an earlier day is not
  /// offered here (it would flash before today's arrives); offline, [advice]
  /// still falls back to it.
  Peeked<DailyAdvice>? peek(String locale) {
    final entry = _cache.store.read(_key(locale));
    if (entry == null || entry.data is! Map) return null;
    try {
      final advice = DailyAdvice.fromJson(Map<String, dynamic>.from(entry.data! as Map), fallbackLocale: locale);
      if (!advice.isToday) return null;
      return (value: advice, fresh: entry.isFresh);
    } on Object {
      return null;
    }
  }

  /// Today's advice: cache → RPC → (none yet) the function, once.
  Future<DailyAdvice> advice(String locale, {bool force = false}) => _cache.get<DailyAdvice>(
    _key(locale),
    // A copy from an earlier day is never "fresh" (offline it is still served).
    forceRefresh: force || _fromEarlierDay(locale),
    fetch: () => _fetch(locale),
    encode: (v) => v.toJson(),
    decode: (j) => DailyAdvice.fromJson(Map<String, dynamic>.from(j! as Map), fallbackLocale: locale),
    policy: _policy,
    isEmpty: (v) => v.isEmpty,
  );

  bool _fromEarlierDay(String locale) {
    final data = _cache.store.read(_key(locale))?.data;
    return data is Map && data['advice_date'] != BdTime.todayIso();
  }

  Future<DailyAdvice> _fetch(String locale) async {
    final row = await _api.stored(locale);
    if (row != null) return DailyAdvice.fromJson(row, fallbackLocale: locale);
    try {
      return DailyAdvice.fromJson(await _api.generate(locale, refresh: false), fallbackLocale: locale);
    } on RateLimitFailure {
      // Today's allowance is used up: show nothing rather than an error.
      return DailyAdvice.empty(locale);
    }
  }

  /// Re-evaluates today's advice from the learner's latest data. The server
  /// answers with the same advice (`unchanged`) when nothing relevant moved,
  /// and allows 3 real refreshes per day ([RateLimitFailure] after that).
  Future<DailyAdvice> regenerate(String locale) async {
    final advice = DailyAdvice.fromJson(await _api.generate(locale, refresh: true), fallbackLocale: locale);
    await _cache.store.write(_key(locale), advice.toJson(), advice.isEmpty ? emptyTtl : BdTime.untilEndOfToday());
    return advice;
  }
}

final dailyAdviceRepositoryProvider = Provider<DailyAdviceRepository>(
  (ref) => DailyAdviceRepository(ref.watch(supabaseProvider), ref.watch(cachedFetcherProvider)),
);
