-- ============================================================================
-- 0002 · Learning catalog & question bank
-- Subjects/topics follow the BPSC BCS preliminary syllabus (200 marks).
-- Every question carries its SOURCE (previous exam, book, newspaper, AI …).
-- The bank is NOT fixed: the daily AI pipeline appends current-affairs
-- questions every day, admins add/import more, and questions built on facts
-- that later change are archived automatically (see 0005 · facts).
-- Correct answers are hidden from clients via column privileges and are only
-- revealed through security-definer RPCs after the user has answered.
-- ============================================================================

-- Functions may reference tables created by later migrations.
set check_function_bodies = off;

create table public.subjects (
  id              smallint primary key,
  code            text not null unique,
  name_bn         text not null,
  name_en         text not null,
  bcs_marks       int not null default 0,
  placement_group text check (placement_group in ('bangla', 'english', 'math', 'gk')),
  icon            text,
  color           text,
  sort            int not null default 0
);
alter table public.subjects enable row level security;
create policy "subjects: readable" on public.subjects for select to anon, authenticated using (true);

create table public.topics (
  id          int primary key,
  subject_id  smallint not null references public.subjects (id) on delete cascade,
  code        text not null unique,
  name_bn     text not null,
  name_en     text not null,
  weight      numeric(5, 2) not null default 1 check (weight > 0),
  is_general  boolean not null default false,
  sort        int not null default 0
);
create index topics_subject_idx on public.topics (subject_id, sort);
alter table public.topics enable row level security;
create policy "topics: readable" on public.topics for select to anon, authenticated using (true);

create table public.exam_types (
  code            text primary key,
  name_bn         text not null,
  name_en         text not null,
  description_bn  text,
  sort            int not null default 0
);
alter table public.exam_types enable row level security;
create policy "exam_types: readable" on public.exam_types for select to anon, authenticated using (true);

-- Upcoming exam dates are approximate until BPSC confirms them. When an admin
-- changes `expected_date`, every active study plan targeting it is re-planned
-- automatically (see 0007 · trigger on_exam_schedule_changed).
create table public.exam_schedules (
  id            bigint generated by default as identity primary key,
  exam_type     text not null references public.exam_types (code),
  title_bn      text not null,
  title_en      text not null,
  stage         text not null default 'preliminary',
  expected_date date not null,
  is_confirmed  boolean not null default false,
  source_url    text,
  notes         text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger exam_schedules_updated_at before update on public.exam_schedules
  for each row execute function public.set_updated_at();
alter table public.exam_schedules enable row level security;
create policy "exam_schedules: readable" on public.exam_schedules for select to authenticated using (is_active or public.is_admin());
create policy "exam_schedules: admin writes" on public.exam_schedules for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

alter table public.profiles
  add constraint profiles_target_schedule_fk
  foreign key (target_schedule_id) references public.exam_schedules (id) on delete set null;

create type public.source_kind as enum
  ('previous_exam', 'book', 'newspaper', 'website', 'ai_generated', 'curated');

create table public.sources (
  id            bigint generated by default as identity primary key,
  kind          public.source_kind not null,
  name          text not null,
  exam_type     text references public.exam_types (code),
  year          int,
  publisher     text,
  url           text,
  license_note  text,
  created_at    timestamptz not null default now(),
  unique (kind, name)
);
alter table public.sources enable row level security;
create policy "sources: readable" on public.sources for select to authenticated using (true);
create policy "sources: admin writes" on public.sources for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Questions
-- ---------------------------------------------------------------------------
create table public.questions (
  id              bigint generated always as identity primary key,
  subject_id      smallint not null references public.subjects (id),
  topic_id        int references public.topics (id),
  stem            text not null check (char_length(stem) between 3 and 2000),
  options         jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) between 2 and 5),
  correct_index   smallint not null,
  explanation     text,
  difficulty      smallint not null default 2 check (difficulty between 1 and 5),
  language        text not null default 'bn' check (language in ('bn', 'en')),
  source_id       bigint references public.sources (id) on delete set null,
  source_ref      text,
  source_url      text,
  exam_tags       text[] not null default '{}',
  year            int,
  status          text not null default 'published' check (status in ('draft', 'published', 'rejected', 'archived')),
  review_status   text not null default 'unverified' check (review_status in ('unverified', 'verified', 'flagged')),
  stem_hash       text generated always as (md5(lower(regexp_replace(stem, '\s+', '', 'g')))) stored,
  embedding       extensions.vector(1536),
  times_answered  int not null default 0,
  times_correct   int not null default 0,
  created_by      uuid references public.profiles (id) on delete set null,
  created_at      timestamptz not null default now(),
  constraint questions_correct_in_range check (correct_index >= 0 and correct_index < jsonb_array_length(options)),
  constraint questions_stem_unique unique (stem_hash)
);
create index questions_subject_topic_idx on public.questions (subject_id, topic_id, id) where status = 'published';
create index questions_source_idx        on public.questions (source_id, id);
create index questions_tags_idx          on public.questions using gin (exam_tags);
create index questions_stem_trgm         on public.questions using gin (stem extensions.gin_trgm_ops);
create index questions_embedding_hnsw    on public.questions using hnsw (embedding extensions.vector_cosine_ops);

-- Questions without an explicit topic fall into their subject's "general" topic,
-- so mastery tracking always has a topic to attribute to.
create or replace function public.questions_default_topic()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.topic_id is null then
    select t.id into new.topic_id from public.topics t
     where t.subject_id = new.subject_id and t.is_general limit 1;
  end if;
  return new;
end $$;
create trigger questions_default_topic before insert or update of subject_id, topic_id on public.questions
  for each row execute function public.questions_default_topic();

alter table public.questions enable row level security;
create policy "questions: published readable" on public.questions for select to authenticated
  using (status = 'published' or public.is_staff());
create policy "questions: staff writes" on public.questions for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- Hide answers + embeddings: clients must select explicit columns.
revoke all on public.questions from anon, authenticated;
grant select (id, subject_id, topic_id, stem, options, difficulty, language, source_id,
              source_ref, source_url, exam_tags, year, status, times_answered, times_correct, created_at)
  on public.questions to authenticated;

-- Every answer a user gives (exam, practice, or "show answer").
create table public.question_attempts (
  id              bigint generated always as identity primary key,
  user_id         uuid not null references public.profiles (id) on delete cascade,
  question_id     bigint not null references public.questions (id) on delete cascade,
  session_id      uuid,
  selected_index  smallint,
  is_correct      boolean,
  mode            text not null check (mode in ('exam', 'practice', 'reveal')),
  created_at      timestamptz not null default now()
);
create index question_attempts_user_idx     on public.question_attempts (user_id, created_at desc);
create index question_attempts_user_q_idx   on public.question_attempts (user_id, question_id, created_at desc);
alter table public.question_attempts enable row level security;
create policy "question_attempts: owner reads" on public.question_attempts
  for select to authenticated using (user_id = (select auth.uid()));
revoke insert, update, delete on public.question_attempts from anon, authenticated;

create table public.bookmarks (
  user_id    uuid not null references public.profiles (id) on delete cascade,
  item_type  text not null check (item_type in ('question', 'note', 'post')),
  item_id    text not null,
  payload    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (user_id, item_type, item_id)
);
create index bookmarks_user_idx on public.bookmarks (user_id, created_at desc);
alter table public.bookmarks enable row level security;
create policy "bookmarks: owner all" on public.bookmarks for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- Public question payload (never includes the answer).
-- ---------------------------------------------------------------------------
create or replace function public.question_public_json(q public.questions)
returns jsonb
language sql immutable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', q.id, 'subject_id', q.subject_id, 'topic_id', q.topic_id, 'stem', q.stem,
    'options', q.options, 'difficulty', q.difficulty, 'language', q.language,
    'source_ref', q.source_ref, 'source_url', q.source_url, 'year', q.year);
$$;

-- Browse/practice questions (keyset pagination by id).
create or replace function public.get_practice_questions(
  p_subject smallint default null, p_topic int default null, p_source bigint default null,
  p_limit int default 20, p_after_id bigint default null, p_unseen_only boolean default false,
  p_search text default null
)
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(public.question_public_json(q) order by q.id), '[]'::jsonb)
    from (
      select q.* from public.questions q
       where q.status = 'published'
         and (p_subject is null or q.subject_id = p_subject)
         and (p_topic is null or q.topic_id = p_topic)
         and (p_source is null or q.source_id = p_source)
         and (p_after_id is null or q.id > p_after_id)
         and (p_search is null or q.stem ilike '%' || p_search || '%')
         and (not p_unseen_only or not exists (
               select 1 from public.question_attempts a
                where a.user_id = auth.uid() and a.question_id = q.id))
         -- never leak today's live daily-exam questions into practice
         and not exists (
               select 1 from public.daily_exams d
                where d.exam_date = public.bd_today() and q.id = any (d.question_ids))
       order by q.id
       limit least(coalesce(p_limit, 20), 50)
    ) q;
$$;

-- True when the question is part of today's daily exam and the caller has not
-- submitted it yet — answers must stay hidden in that case.
create or replace function public.is_live_daily_question(p_question bigint)
returns boolean
language sql stable security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.daily_exams d
     where d.exam_date = public.bd_today()
       and p_question = any (d.question_ids)
       and not exists (
         select 1 from public.exam_sessions s
          where s.user_id = auth.uid() and s.daily_exam_id = d.id and s.status = 'submitted'));
$$;

create or replace function public.answer_practice_question(p_question bigint, p_selected smallint)
returns jsonb
language plpgsql security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_q   public.questions;
  v_ok  boolean;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode = 'PT401'; end if;
  perform public.enforce_rate_limit('practice_answer', 300, 3600);
  if public.is_live_daily_question(p_question) then
    raise exception 'question_locked' using errcode = 'PT403';
  end if;

  select * into v_q from public.questions where id = p_question and status = 'published';
  if not found then raise exception 'question_not_found' using errcode = 'PT404'; end if;

  v_ok := (p_selected = v_q.correct_index);
  insert into public.question_attempts (user_id, question_id, selected_index, is_correct, mode)
  values (v_uid, p_question, p_selected, v_ok, 'practice');
  update public.questions
     set times_answered = times_answered + 1,
         times_correct  = times_correct + case when v_ok then 1 else 0 end
   where id = p_question;
  perform public.update_mastery(v_uid, v_q.topic_id, v_ok, 0.15);
  perform public.touch_streak(v_uid);

  return jsonb_build_object('is_correct', v_ok, 'correct_index', v_q.correct_index,
                            'explanation', v_q.explanation);
end $$;

create or replace function public.reveal_answer(p_question bigint)
returns jsonb
language plpgsql security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_q   public.questions;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode = 'PT401'; end if;
  perform public.enforce_rate_limit('reveal_answer', 600, 3600);
  if public.is_live_daily_question(p_question) then
    raise exception 'question_locked' using errcode = 'PT403';
  end if;
  select * into v_q from public.questions where id = p_question and status = 'published';
  if not found then raise exception 'question_not_found' using errcode = 'PT404'; end if;
  insert into public.question_attempts (user_id, question_id, mode) values (v_uid, p_question, 'reveal');
  return jsonb_build_object('correct_index', v_q.correct_index, 'explanation', v_q.explanation);
end $$;

-- "ভুলের খাতা": questions whose latest graded attempt was wrong.
create or replace function public.get_wrong_answers(
  p_limit int default 20, p_before timestamptz default null, p_subject smallint default null
)
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  with latest as (
    select distinct on (a.question_id) a.question_id, a.selected_index, a.is_correct, a.created_at
      from public.question_attempts a
     where a.user_id = auth.uid() and a.mode in ('exam', 'practice')
     order by a.question_id, a.created_at desc
  )
  select coalesce(jsonb_agg(
           public.question_public_json(q) || jsonb_build_object(
             'correct_index', q.correct_index, 'explanation', q.explanation,
             'selected_index', l.selected_index, 'attempted_at', l.created_at)
           order by l.created_at desc), '[]'::jsonb)
    from (select * from latest
           where is_correct = false and (p_before is null or created_at < p_before)
           order by created_at desc
           limit least(coalesce(p_limit, 20), 50)) l
    join public.questions q on q.id = l.question_id
   where p_subject is null or q.subject_id = p_subject;
$$;

-- Previous-exam sources with question counts (for "বিগত বছরের প্রশ্ন").
create or replace function public.get_question_sources(p_kind public.source_kind default null)
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', s.id, 'kind', s.kind, 'name', s.name, 'exam_type', s.exam_type, 'year', s.year,
           'publisher', s.publisher, 'url', s.url, 'question_count', c.cnt)
         order by s.year desc nulls last, s.name), '[]'::jsonb)
    from public.sources s
    join lateral (select count(*) as cnt from public.questions q
                   where q.source_id = s.id and q.status = 'published') c on true
   where (p_kind is null or s.kind = p_kind) and c.cnt > 0;
$$;

-- Subject list with question counts + the caller's mastery (one round trip).
create or replace function public.get_subjects_overview()
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', s.id, 'code', s.code, 'name_bn', s.name_bn, 'name_en', s.name_en,
           'bcs_marks', s.bcs_marks, 'icon', s.icon, 'color', s.color,
           'question_count', (select count(*) from public.questions q where q.subject_id = s.id and q.status = 'published'),
           'mastery', (select round(avg(m.mastery)::numeric, 3) from public.user_topic_mastery m
                         join public.topics t on t.id = m.topic_id
                        where m.user_id = auth.uid() and t.subject_id = s.id),
           'topics', (select coalesce(jsonb_agg(jsonb_build_object(
                         'id', t.id, 'code', t.code, 'name_bn', t.name_bn, 'name_en', t.name_en,
                         'mastery', (select m.mastery from public.user_topic_mastery m
                                      where m.user_id = auth.uid() and m.topic_id = t.id))
                       order by t.sort), '[]'::jsonb)
                        from public.topics t where t.subject_id = s.id))
         order by s.sort), '[]'::jsonb)
    from public.subjects s;
$$;
