-- ============================================================================
-- 0005 · Current affairs (সাম্প্রতিক): news → facts → daily notes → daily exam
--
-- Pipeline (Edge Functions, scheduled by pg_cron — see 0009):
--   ingest-news          RSS from BD + international outlets → news_articles
--   generate-daily-notes AI extracts exam-relevant FACTS, de-duplicates them
--                        semantically against the permanent `facts` store,
--                        detects facts that SUPERSEDE older ones, and writes
--                        the day's notes
--   generate-daily-exam  MCQs from today's facts → questions (kept forever)
--
-- Notes are visible ONLY on their own Bangladesh calendar day (RLS), yet stay
-- in the database forever. Facts and their questions keep growing every day;
-- a superseded fact archives the questions built on it.
-- ============================================================================

-- Functions may reference tables created by later migrations.
set check_function_bodies = off;

create table public.news_sources (
  id             smallint generated by default as identity primary key,
  name           text not null,
  homepage       text,
  rss_url        text not null unique,
  language       text not null default 'bn' check (language in ('bn', 'en')),
  region         text not null default 'BD' check (region in ('BD', 'INT')),
  category_hint  text,
  priority       smallint not null default 5,
  enabled        boolean not null default true,
  last_fetched_at timestamptz,
  last_error     text,
  fail_count     int not null default 0,
  created_at     timestamptz not null default now()
);
alter table public.news_sources enable row level security;
create policy "news_sources: staff" on public.news_sources for all to authenticated
  using (public.is_staff()) with check (public.is_admin());

create table public.news_articles (
  id           bigint generated always as identity primary key,
  source_id    smallint references public.news_sources (id) on delete set null,
  url          text not null,
  url_hash     text not null unique,
  title        text not null,
  summary      text,
  image_url    text,
  language     text,
  published_at timestamptz,
  fetched_at   timestamptz not null default now(),
  content_hash text,
  embedding    extensions.vector(1536),
  processed_at timestamptz
);
create index news_articles_published_idx  on public.news_articles (published_at desc);
create index news_articles_unprocessed_idx on public.news_articles (fetched_at) where processed_at is null;
alter table public.news_articles enable row level security;
create policy "news_articles: staff read" on public.news_articles for select to authenticated using (public.is_staff());

-- Permanent, ever-growing knowledge base of exam-relevant facts.
create table public.facts (
  id                  bigint generated always as identity primary key,
  fact                text not null,
  category            text not null,
  subject_id          smallint references public.subjects (id),
  entity              text,
  is_time_sensitive   boolean not null default true,
  status              text not null default 'active' check (status in ('active', 'superseded', 'retracted')),
  first_seen_date     date not null default public.bd_today(),
  last_confirmed_date date not null default public.bd_today(),
  superseded_by       bigint references public.facts (id),
  superseded_at       timestamptz,
  source_links        jsonb not null default '[]'::jsonb,
  source_article_ids  bigint[] not null default '{}',
  embedding           extensions.vector(1536),
  created_at          timestamptz not null default now()
);
create index facts_active_idx    on public.facts (category, first_seen_date desc) where status = 'active';
create index facts_entity_idx    on public.facts (entity) where entity is not null;
create index facts_embedding_hnsw on public.facts using hnsw (embedding extensions.vector_cosine_ops);
alter table public.facts enable row level security;
create policy "facts: staff read" on public.facts for select to authenticated using (public.is_staff());
create policy "facts: staff write" on public.facts for update to authenticated using (public.is_staff()) with check (public.is_staff());

alter table public.questions add column fact_id bigint references public.facts (id) on delete set null;
create index questions_fact_idx on public.questions (fact_id) where fact_id is not null;

-- When a fact is superseded/retracted, archive every question built on it so
-- learners never practise an outdated answer.
create or replace function public.facts_after_status_change()
returns trigger
language plpgsql security definer
set search_path = ''
as $$
begin
  if new.status <> 'active' and old.status = 'active' then
    update public.questions set status = 'archived'
     where fact_id = new.id and status = 'published';
  end if;
  return new;
end $$;
create trigger facts_after_status_change after update of status on public.facts
  for each row execute function public.facts_after_status_change();

-- ---------------------------------------------------------------------------
-- Daily notes
-- ---------------------------------------------------------------------------
create table public.daily_notes (
  id                 bigint generated always as identity primary key,
  note_date          date not null default public.bd_today(),
  category           text not null check (category in (
                       'bangladesh', 'international', 'economy', 'science_tech', 'sports',
                       'environment', 'awards_people', 'organizations', 'days_events', 'misc')),
  title              text not null,
  summary            text not null,
  key_facts          jsonb not null default '[]'::jsonb,
  probable_questions jsonb not null default '[]'::jsonb,
  importance         smallint not null default 3 check (importance between 1 and 5),
  source_links       jsonb not null default '[]'::jsonb,
  source_article_ids bigint[] not null default '{}',
  fact_ids           bigint[] not null default '{}',
  status             text not null default 'published' check (status in ('draft', 'published', 'archived')),
  embedding          extensions.vector(1536),
  model              text,
  created_at         timestamptz not null default now()
);
create index daily_notes_day_idx on public.daily_notes (note_date, importance desc, id) where status = 'published';
alter table public.daily_notes enable row level security;
-- ★ Requirement: notes are only visible on their own day; history stays in DB.
create policy "daily_notes: today only" on public.daily_notes for select to authenticated
  using ((status = 'published' and note_date = public.bd_today() and public.has_feature('daily_notes'))
         or public.is_staff());
create policy "daily_notes: staff writes" on public.daily_notes for update to authenticated
  using (public.is_staff()) with check (public.is_staff());
revoke all on public.daily_notes from anon, authenticated;
grant select (id, note_date, category, title, summary, key_facts, probable_questions, importance,
              source_links, status, created_at) on public.daily_notes to authenticated;
grant update (title, summary, key_facts, probable_questions, importance, status) on public.daily_notes to authenticated;

-- Downloads of the day's notes (rewarded ad, or ad-free add-on).
create table public.note_downloads (
  user_id    uuid not null references public.profiles (id) on delete cascade,
  note_date  date not null,
  method     text not null check (method in ('ad', 'addon')),
  created_at timestamptz not null default now(),
  primary key (user_id, note_date, method)
);
alter table public.note_downloads enable row level security;
create policy "note_downloads: owner reads" on public.note_downloads for select to authenticated
  using (user_id = (select auth.uid()));
revoke insert, update, delete on public.note_downloads from anon, authenticated;

-- Called by the app after a rewarded ad completes (or for ad-free users).
create or replace function public.claim_note_download(p_method text default 'ad')
returns jsonb
language plpgsql security definer
set search_path = ''
as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode = 'PT401'; end if;
  if p_method not in ('ad', 'addon') then raise exception 'invalid_method'; end if;
  if p_method = 'addon' and not public.user_has_feature(v_uid, 'ad_free') then
    raise exception 'feature_locked' using errcode = 'PT402', detail = 'ad_free';
  end if;
  perform public.enforce_rate_limit('note_download', 20, 0);
  if not exists (select 1 from public.daily_notes where note_date = public.bd_today() and status = 'published') then
    raise exception 'no_notes_today' using errcode = 'PT404';
  end if;
  insert into public.note_downloads (user_id, note_date, method) values (v_uid, public.bd_today(), p_method)
  on conflict do nothing;
  return jsonb_build_object('allowed', true, 'note_date', public.bd_today());
end $$;

-- ---------------------------------------------------------------------------
-- Daily exam (built from the day's facts)
-- ---------------------------------------------------------------------------
create table public.daily_exams (
  id               bigint generated always as identity primary key,
  exam_date        date not null unique default public.bd_today(),
  title_bn         text not null,
  question_ids     bigint[] not null,
  duration_minutes int not null default 10,
  negative_mark    numeric(3, 2) not null default 0.5,
  status           text not null default 'published' check (status in ('draft', 'published')),
  created_at       timestamptz not null default now()
);
alter table public.daily_exams enable row level security;
create policy "daily_exams: today readable" on public.daily_exams for select to authenticated
  using ((status = 'published' and exam_date = public.bd_today()) or public.is_staff());

-- Notes of today, in one round trip, with download state for the caller.
create or replace function public.get_today_notes()
returns jsonb
language sql stable security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'note_date', public.bd_today(),
    'notes', coalesce((select jsonb_agg(jsonb_build_object(
                'id', n.id, 'category', n.category, 'title', n.title, 'summary', n.summary,
                'key_facts', n.key_facts, 'probable_questions', n.probable_questions,
                'importance', n.importance, 'source_links', n.source_links, 'created_at', n.created_at)
              order by n.importance desc, n.id)
              from public.daily_notes n
             where n.note_date = public.bd_today() and n.status = 'published'), '[]'::jsonb),
    'downloaded', exists (select 1 from public.note_downloads d
                           where d.user_id = auth.uid() and d.note_date = public.bd_today()),
    'daily_exam', (select jsonb_build_object('id', e.id, 'title_bn', e.title_bn,
                          'question_count', cardinality(e.question_ids),
                          'duration_minutes', e.duration_minutes)
                     from public.daily_exams e
                    where e.exam_date = public.bd_today() and e.status = 'published'));
$$;

-- Admin/pipeline helper: nearest active facts to an embedding.
create or replace function public.match_facts(
  p_embedding extensions.vector, p_threshold real default 0.85, p_limit int default 5
)
returns table (id bigint, fact text, entity text, category text, first_seen_date date, similarity real)
language sql stable security definer
set search_path = ''
as $$
  select f.id, f.fact, f.entity, f.category, f.first_seen_date,
         (1 - (f.embedding operator(extensions.<=>) p_embedding))::real
    from public.facts f
   where f.status = 'active' and f.embedding is not null
     and 1 - (f.embedding operator(extensions.<=>) p_embedding) >= p_threshold
   order by f.embedding operator(extensions.<=>) p_embedding
   limit p_limit;
$$;
revoke execute on function public.match_facts(extensions.vector, real, int) from public, anon, authenticated;

create or replace function public.match_questions(
  p_embedding extensions.vector, p_threshold real default 0.9, p_limit int default 5
)
returns table (id bigint, stem text, similarity real)
language sql stable security definer
set search_path = ''
as $$
  select q.id, q.stem, (1 - (q.embedding operator(extensions.<=>) p_embedding))::real
    from public.questions q
   where q.embedding is not null and q.status in ('published', 'draft')
     and 1 - (q.embedding operator(extensions.<=>) p_embedding) >= p_threshold
   order by q.embedding operator(extensions.<=>) p_embedding
   limit p_limit;
$$;
revoke execute on function public.match_questions(extensions.vector, real, int) from public, anon, authenticated;
