-- ============================================================================
-- 0007 · Onboarding interview, AI study plan, daily routine, re-planning
--
-- • The plan itself is generated by the `generate-study-plan` Edge Function.
-- • ★ Users only ever see their plan PARTIALLY: RLS exposes days up to
--   today + 2. Everything beyond is available only as an aggregate overview.
-- • Free "weak topic" days are resolved on the day itself from live mastery.
-- • If BPSC moves the exam date, every affected plan is queued for re-planning.
-- ============================================================================

-- Functions may reference tables created by later migrations.
set check_function_bodies = off;

create table public.onboarding_interviews (
  user_id      uuid primary key references public.profiles (id) on delete cascade,
  answers      jsonb not null default '{}'::jsonb,
  followups    jsonb not null default '[]'::jsonb,
  ai_profile   jsonb,
  completed_at timestamptz,
  updated_at   timestamptz not null default now()
);
alter table public.onboarding_interviews enable row level security;
create policy "onboarding_interviews: owner all" on public.onboarding_interviews for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create trigger onboarding_interviews_updated_at before update on public.onboarding_interviews
  for each row execute function public.set_updated_at();

create table public.study_plans (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  schedule_id   bigint references public.exam_schedules (id) on delete set null,
  exam_date     date not null,
  start_date    date not null,
  daily_minutes int not null,
  status        text not null default 'active' check (status in ('active', 'superseded', 'completed')),
  version       int not null default 1,
  summary       jsonb not null default '{}'::jsonb,
  ai_tips       jsonb not null default '[]'::jsonb,
  generated_by  text,
  created_at    timestamptz not null default now()
);
create unique index study_plans_one_active on public.study_plans (user_id) where status = 'active';
alter table public.study_plans enable row level security;
create policy "study_plans: owner reads" on public.study_plans for select to authenticated
  using (user_id = (select auth.uid()));
revoke insert, update, delete on public.study_plans from anon, authenticated;

create table public.study_plan_days (
  id              bigint generated always as identity primary key,
  plan_id         uuid not null references public.study_plans (id) on delete cascade,
  user_id         uuid not null references public.profiles (id) on delete cascade,
  day_date        date not null,
  day_index       int not null,
  kind            text not null check (kind in ('study', 'revision', 'weak_topic_exam', 'model_test', 'rest')),
  title_bn        text not null,
  items           jsonb not null default '[]'::jsonb,
  target_minutes  int not null default 0,
  completed_items int not null default 0,
  total_items     int not null default 0,
  status          text not null default 'pending' check (status in ('pending', 'partial', 'done', 'missed')),
  completed_at    timestamptz,
  unique (plan_id, day_date)
);
create index study_plan_days_user_idx on public.study_plan_days (user_id, day_date);
alter table public.study_plan_days enable row level security;
-- ★ partial visibility
create policy "study_plan_days: owner sees up to today+2" on public.study_plan_days for select to authenticated
  using (user_id = (select auth.uid()) and day_date <= public.bd_today() + 2);
revoke insert, update, delete on public.study_plan_days from anon, authenticated;

create table public.plan_replan_jobs (
  id           bigint generated always as identity primary key,
  user_id      uuid not null references public.profiles (id) on delete cascade,
  reason       text not null,
  created_at   timestamptz not null default now(),
  processed_at timestamptz,
  error        text
);
create index plan_replan_jobs_pending_idx on public.plan_replan_jobs (created_at) where processed_at is null;
alter table public.plan_replan_jobs enable row level security;

-- ---------------------------------------------------------------------------
-- Routine helpers
-- ---------------------------------------------------------------------------
create or replace function public._complete_plan_item(p_user uuid, p_day bigint, p_key text)
returns jsonb
language plpgsql security definer
set search_path = ''
as $$
declare
  v_day   public.study_plan_days;
  v_done  int;
begin
  select * into v_day from public.study_plan_days
   where id = p_day and user_id = p_user for update;
  if not found then return null; end if;

  update public.study_plan_days d
     set items = (select jsonb_agg(case when e.it ->> 'key' = p_key
                                        then e.it || jsonb_build_object('done', true, 'done_at', now())
                                        else e.it end order by e.ord)
                    from jsonb_array_elements(d.items) with ordinality e(it, ord))
   where d.id = p_day
  returning * into v_day;

  select count(*) into v_done from jsonb_array_elements(v_day.items) it
   where coalesce((it ->> 'done')::boolean, false);

  update public.study_plan_days
     set completed_items = v_done,
         status = case when v_done >= total_items then 'done' when v_done > 0 then 'partial' else status end,
         completed_at = case when v_done >= total_items then coalesce(completed_at, now()) end
   where id = p_day
  returning * into v_day;

  perform public.touch_streak(p_user);
  return to_jsonb(v_day);
end $$;
revoke execute on function public._complete_plan_item(uuid, bigint, text) from public, anon, authenticated;

create or replace function public.complete_plan_item(p_day bigint, p_key text)
returns jsonb
language plpgsql security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.study_plan_days
                  where id = p_day and user_id = auth.uid() and day_date <= public.bd_today()) then
    raise exception 'day_not_available' using errcode = 'PT403';
  end if;
  return public._complete_plan_item(auth.uid(), p_day, p_key);
end $$;

create or replace function public._weak_topics(p_user uuid, p_limit int default 4)
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
           'topic_id', t.id, 'name_bn', t.name_bn, 'name_en', t.name_en,
           'subject_id', t.subject_id, 'mastery', round(m.mastery::numeric, 2)) order by m.mastery), '[]'::jsonb)
    from (select * from public.user_topic_mastery where user_id = p_user
           order by mastery asc, attempts desc limit p_limit) m
    join public.topics t on t.id = m.topic_id;
$$;

-- Everything the Home screen needs about today's routine in one call.
create or replace function public.get_today_routine()
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  with plan as (
    select * from public.study_plans where user_id = auth.uid() and status = 'active'
  ), today as (
    select d.* from public.study_plan_days d join plan p on p.id = d.plan_id
     where d.day_date = public.bd_today()
  )
  select jsonb_build_object(
    'has_plan', exists (select 1 from plan),
    'plan', (select jsonb_build_object('id', p.id, 'exam_date', p.exam_date, 'start_date', p.start_date,
                                       'days_left', p.exam_date - public.bd_today(),
                                       'daily_minutes', p.daily_minutes, 'version', p.version)
               from plan p),
    'today', (select to_jsonb(t) || case when t.kind = 'weak_topic_exam'
                                         then jsonb_build_object('weak_topics', public._weak_topics(auth.uid()))
                                         else '{}'::jsonb end
                from today t),
    'upcoming', coalesce((select jsonb_agg(jsonb_build_object('id', d.id, 'day_date', d.day_date, 'kind', d.kind,
                                                              'title_bn', d.title_bn, 'target_minutes', d.target_minutes)
                                           order by d.day_date)
                            from public.study_plan_days d join plan p on p.id = d.plan_id
                           where d.day_date between public.bd_today() + 1 and public.bd_today() + 2), '[]'::jsonb));
$$;

-- Aggregate overview of the WHOLE plan without revealing its details.
create or replace function public.get_plan_overview()
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  with plan as (select * from public.study_plans where user_id = auth.uid() and status = 'active'),
  days as (select d.* from public.study_plan_days d join plan p on p.id = d.plan_id)
  select case when not exists (select 1 from plan) then jsonb_build_object('has_plan', false) else
    (select jsonb_build_object(
      'has_plan', true,
      'id', p.id, 'exam_date', p.exam_date, 'start_date', p.start_date, 'version', p.version,
      'daily_minutes', p.daily_minutes,
      'total_days', (select count(*) from days),
      'days_left', greatest(p.exam_date - public.bd_today(), 0),
      'done_days', (select count(*) from days where status = 'done'),
      'partial_days', (select count(*) from days where status = 'partial'),
      'missed_days', (select count(*) from days where status = 'missed'),
      'locked_days', (select count(*) from days where day_date > public.bd_today() + 2),
      'kinds', (select jsonb_object_agg(kind, c) from (select kind, count(*) c from days group by kind) k),
      'summary', p.summary,
      'ai_tips', p.ai_tips,
      'recent', coalesce((select jsonb_agg(jsonb_build_object('id', d.id, 'day_date', d.day_date, 'kind', d.kind,
                                                              'title_bn', d.title_bn, 'status', d.status,
                                                              'completed_items', d.completed_items,
                                                              'total_items', d.total_items)
                                           order by d.day_date)
                            from days d
                           where d.day_date between public.bd_today() - 6 and public.bd_today() + 2), '[]'::jsonb))
      from plan p)
  end;
$$;

create or replace function public.request_replan(p_reason text default 'user_request')
returns void
language plpgsql security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'not_authenticated' using errcode = 'PT401'; end if;
  perform public.enforce_rate_limit('replan', 5, 0);
  insert into public.plan_replan_jobs (user_id, reason) values (auth.uid(), left(coalesce(p_reason, 'user_request'), 200));
  perform public.invoke_edge_function('generate-study-plan', jsonb_build_object('mode', 'jobs'), 120000);
end $$;

-- Exam date moved → re-plan every active plan that targets this schedule.
create or replace function public.on_exam_schedule_changed()
returns trigger
language plpgsql security definer
set search_path = ''
as $$
declare r record;
begin
  if new.expected_date is distinct from old.expected_date then
    for r in select distinct user_id from public.study_plans
              where status = 'active' and (schedule_id = new.id) loop
      insert into public.plan_replan_jobs (user_id, reason) values (r.user_id, 'exam_date_changed');
      perform public.notify_user(r.user_id, 'plan_update', 'পরীক্ষার তারিখ পরিবর্তিত হয়েছে',
        new.title_bn || ' এর নতুন সম্ভাব্য তারিখ ' || to_char(new.expected_date, 'DD-MM-YYYY') ||
        '। আপনার রুটিন নতুন তারিখ অনুযায়ী আপডেট করা হচ্ছে।',
        jsonb_build_object('schedule_id', new.id), null, 'routine');
    end loop;
    perform public.invoke_edge_function('generate-study-plan', jsonb_build_object('mode', 'jobs'), 120000);
  end if;
  return new;
end $$;
create trigger exam_schedules_changed after update on public.exam_schedules
  for each row execute function public.on_exam_schedule_changed();
